    - name: Verify CODEX_TOKEN Access
      env:
        CODEX_TOKEN: ${{ secrets.CODEX_TOKEN }}
      run: |
        python - <<EOF
import os
from github import Github

token = os.environ.get('CODEX_TOKEN')
if not token:
    raise Exception('CODEX_TOKEN is not set')

g = Github(token)
user = g.get_user()
print(f'✅ Authenticated as: {user.login}')
EOF
